# Generated by Django 5.0.2 on 2024-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="user_type", field=models.CharField(max_length=255),
        ),
    ]
