# Generated by Django 5.0.2 on 2024-06-06 04:12

import django.db.models.deletion
import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_applyproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="payment_status",
            field=models.ForeignKey(
                default=register.models.Projects.get_default_payment_status,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.paymentstatus",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_status",
            field=models.ForeignKey(
                default=register.models.Projects.get_default_project_status,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.projectstatus",
            ),
        ),
    ]
