# Generated by Django 5.0.2 on 2024-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_client_projects_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
