# Generated by Django 5.0.2 on 2024-06-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_applyproject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="applied_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="where_did_you_heard",
            field=models.CharField(
                choices=[
                    ("I", "Instagram"),
                    ("Fa", "Facebook"),
                    ("F", "Friends"),
                    ("T", "Twitter"),
                    ("G", "Google"),
                    ("O", "Others"),
                    ("Y", "Youtube"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.TextField()),
                ("state", models.TextField()),
                ("city", models.TextField()),
                ("zip_code", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
