# Generated by Django 5.0.2 on 2024-06-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_projects_applied_count_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="applyproject", unique_together={("project_id", "frelancer_id")},
        ),
    ]
