# Generated by Django 5.0.2 on 2024-03-08 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_alter_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="projects_uploaded",
            field=models.ManyToManyField(
                blank=True, related_name="uploaded_by_clients", to="register.projects"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
