# Generated by Django 5.0.2 on 2024-08-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_alter_applyproject_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelancerLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BE", "Beginner"),
                            ("IN", "Intermediate"),
                            ("EX", "Expert"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="level",
            field=models.ForeignKey(
                default="BE",
                on_delete=django.db.models.deletion.CASCADE,
                to="register.freelancerlevel",
            ),
        ),
    ]
