# Generated by Django 5.0.2 on 2024-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_alter_client_projects_uploaded_alter_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="projects_uploaded",
            field=models.ManyToManyField(
                related_name="uploaded_by_clients", to="register.projects"
            ),
        ),
    ]
