# Generated by Django 5.0.2 on 2024-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0009_alter_client_projects_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="projects_uploaded",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="uploaded_by_clients",
                to="register.projects",
            ),
        ),
    ]
