# Generated by Django 5.0.2 on 2024-08-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0009_freelancerlevel_alter_address_user_freelancer_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.freelancerlevel",
            ),
        ),
    ]
