# Generated by Django 5.0.2 on 2024-03-27 13:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0010_alter_client_projects_uploaded"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="projects_uploaded",),
        migrations.RemoveField(model_name="projects", name="freelancer",),
        migrations.AddField(
            model_name="projects",
            name="project_assigned_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="projects",
            name="payment_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.paymentstatus",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.projectstatus",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="skills_required",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=[], size=None
            ),
        ),
        migrations.AlterField(
            model_name="projectstatus",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("O", "Onging"),
                    ("P", "Paused"),
                    ("UN", "UnAssigned"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="ProjectsAssigned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frelancers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.freelancer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.projects",
                    ),
                ),
            ],
        ),
    ]
