# Generated by Django 5.0.2 on 2024-03-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0011_remove_client_projects_uploaded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="payment_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.paymentstatus",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.projectstatus",
            ),
        ),
    ]
