# Generated by Django 5.0.2 on 2024-03-27 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0012_alter_projects_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="skills_required",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
