# Generated by Django 5.0.2 on 2024-03-30 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0014_rename_frelancers_projectsassigned_frelancer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsassigned",
            name="assigned_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectsassigned",
            name="revoke",
            field=models.BooleanField(default=False),
        ),
    ]
