# Generated by Django 5.0.2 on 2024-08-18 09:45

import django.contrib.postgres.fields
import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("freelancer", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("C", "Completed"),
                            ("O", "Onging"),
                            ("P", "Paused"),
                            ("UN", "UnAssigned"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_category",
                    models.CharField(
                        choices=[
                            ("R", "Research"),
                            ("D", "Design"),
                            ("Dev", "Development"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("project_price", models.IntegerField()),
                ("project_deadline", models.DateTimeField()),
                (
                    "skills_required",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("project_assigned_status", models.BooleanField(default=False)),
                ("applied_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_created",
                        to="client.client",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        default=project.models.Projects.get_default_payment_status,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentstatus",
                    ),
                ),
                (
                    "project_status",
                    models.ForeignKey(
                        default=project.models.Projects.get_default_project_status,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectsAssigned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("revoke", models.BooleanField(default=False)),
                (
                    "frelancer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="freelancer.freelancer",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("proposal", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PA", "Pending Approval"),
                            ("AC", "Accepted"),
                            ("RE", "Rejected"),
                        ],
                        default="PA",
                        max_length=2,
                    ),
                ),
                (
                    "frelancer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="freelancer.freelancer",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
            ],
            options={"unique_together": {("project_id", "frelancer_id")},},
        ),
    ]
