# Generated by Django 5.0.2 on 2024-08-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyproject',
            old_name='frelancer_id',
            new_name='frelancer',
        ),
        migrations.RenameField(
            model_name='applyproject',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectsassigned',
            old_name='frelancer_id',
            new_name='frelancer',
        ),
        migrations.RenameField(
            model_name='projectsassigned',
            old_name='project_id',
            new_name='project',
        ),
    ]
