# Generated by Django 5.0.2 on 2025-05-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_frelancer_id_applyproject_frelancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsassigned',
            old_name='frelancer',
            new_name='freelancer',
        ),
    ]
