# Generated by Django 5.0.2 on 2025-05-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancer_updated_at_and_more'),
        ('project', '0003_rename_frelancer_projectsassigned_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyproject',
            old_name='frelancer',
            new_name='freelancer',
        ),
        migrations.AlterUniqueTogether(
            name='applyproject',
            unique_together={('project', 'freelancer')},
        ),
    ]
