# Generated by Django 5.0.2 on 2024-08-18 09:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profession", models.CharField(max_length=255)),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("reason_to_join", models.TextField()),
                (
                    "where_did_you_heard",
                    models.CharField(
                        choices=[
                            ("I", "Instagram"),
                            ("Fa", "Facebook"),
                            ("F", "Friends"),
                            ("T", "Twitter"),
                            ("G", "Google"),
                            ("O", "Others"),
                            ("Y", "Youtube"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("bio", models.TextField()),
            ],
        ),
    ]
