# Generated by Django 5.0.2 on 2024-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='where_did_you_heard',
            field=models.CharField(choices=[('I', 'Instagram'), ('Fa', 'Facebook'), ('F', 'Friends'), ('T', 'Twitter'), ('TM', 'Team Member'), ('G', 'Google'), ('O', 'Others'), ('Y', 'Youtube')], max_length=10),
        ),
    ]
